###
#Login API
POST http://localhost:3500/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "identity" : "buzz@gmail.com",
    "password" : "12345678"
}

###

POST http://localhost:3500/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email" : "woody2@gmail.com",
    "mobile" : "1234567890111" ,
    "password" : "12345678",
    "confirmPassword" : "12345678",
    "firstName" : "woody",
    "lastName" : "woody the sherief"
}

###

GET http://localhost:3500/api/auth/me HTTP/1.1

###


POST http://localhost:3500/api/post HTTP/1.1
Content-Type: application/json

{
    "message" : "hello"
}
